Repository Panoptimize/FrontEnd, pull requests merged in 2024-06, with the labels that each got.

#187 PillTest
  src/components/Pill/Pill.tsx
  src/components/Pill/__tests__/Pill.test.tsx
Labels: documentation, enhancement

#199 User auth test
  src/App.test.tsx
  src/pages/Login/__tests__/Login.test.tsx
  src/setupTests.ts
Labels: documentation

#200 Button tests and certain fixes
  src/components/Button/Button.css
  src/components/Button/Button.tsx
  src/components/Button/__test___/Button.test.tsx
  src/components/Button/types.ts
Labels: documentation

#202 Creación de tests para el componente NotesRow
  src/components/NotesRow/NotesRow.tsx
  src/components/NotesRow/__tests__/NotesRow.test.tsx
Labels: documentation

#206 Tests for NotesTable
  src/components/NotesRow/__tests__/NotesRow.test.tsx
  src/components/NotesTable/NotesTable.tsx
  src/components/NotesTable/__tests__/NotesTable.test.tsx
Labels: documentation

#211 Front end notes agent metrics integration
  src/components/AgentCard/AgentCard.tsx
  src/components/AgentTableRow/AgentTableRow.tsx
  src/components/NoteCard/NoteCard.tsx
  src/components/NoteCard/types.ts
  src/components/NoteInputs/NoteInputs.tsx
  src/components/NotesTable/NotesTable.tsx
Labels: enhancement

#225 Enchancement for NotesRow and NotesTable tests.
  src/components/NotesRow/__tests__/NotesRow.test.tsx
  src/components/NotesTable/__tests__/NotesTable.test.tsx
Labels: enhancement

#229 Tesgting as i could.
  src/pages/Dashboard/__tests__/Dashboard.test.tsx
Labels: enhancement

#227 New tests for 100% for AgentTableRow and Password Reset
  src/components/AgentTable/AgentTable.stories.tsx
  src/components/AgentTableRow/AgentTableRow.stories.tsx
  src/components/AgentTableRow/__tests__/AgentTableRow.test.tsx
  src/pages/PasswordReset/__tests__/PasswordReset.test.tsx
Labels: documentation
